ALTER TABLE `users`
  MODIFY COLUMN `role` ENUM('ADMIN', 'USER', 'FINANCE_MANAGER', 'ACCOUNTANT', 'CASHIER') NOT NULL DEFAULT 'ACCOUNTANT';

UPDATE `users` SET `role` = 'ACCOUNTANT' WHERE `role` = 'USER';

ALTER TABLE `users`
  MODIFY COLUMN `role` ENUM('ADMIN', 'FINANCE_MANAGER', 'ACCOUNTANT', 'CASHIER') NOT NULL DEFAULT 'ACCOUNTANT';

ALTER TABLE `refresh_tokens`
  ADD COLUMN `last_activity_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) AFTER `expires_at`;

CREATE TABLE `system_settings` (
  `key` VARCHAR(100) NOT NULL,
  `value` VARCHAR(500) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`key`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
