-- Add direct-method cash flow mapping value types.
ALTER TABLE `report_items`
  MODIFY COLUMN `value_type` ENUM(
    'OPENING_BALANCE', 'CLOSING_BALANCE', 'PERIOD_DEBIT', 'PERIOD_CREDIT',
    'PERIOD_NET', 'YEAR_TO_DATE_DEBIT', 'YEAR_TO_DATE_CREDIT',
    'YEAR_TO_DATE_NET', 'CASH_INFLOW', 'CASH_OUTFLOW'
  ) NULL;

ALTER TABLE `report_item_account_mappings`
  MODIFY COLUMN `value_type` ENUM(
    'OPENING_BALANCE', 'CLOSING_BALANCE', 'PERIOD_DEBIT', 'PERIOD_CREDIT',
    'PERIOD_NET', 'YEAR_TO_DATE_DEBIT', 'YEAR_TO_DATE_CREDIT',
    'YEAR_TO_DATE_NET', 'CASH_INFLOW', 'CASH_OUTFLOW'
  ) NOT NULL;
