import { Static, Type } from "@sinclair/typebox";
export const CodeParamsSchema = Type.Object({ code: Type.String({ minLength: 1, maxLength: 64 }) });
export const IdParamsSchema = Type.Object({ id: Type.Integer({ minimum: 1 }) });
export const CategoryBodySchema = Type.Object({ code: Type.String({ minLength: 1, maxLength: 64 }), description: Type.Optional(Type.Union([Type.String({ maxLength: 500 }), Type.Null()])), sortOrder: Type.Optional(Type.Integer()), enabled: Type.Optional(Type.Boolean()) }, { additionalProperties: false });
export const CategoryUpdateBodySchema = Type.Partial(Type.Omit(CategoryBodySchema, ["code"]));
export const ItemBodySchema = Type.Object({ code: Type.String({ minLength: 1, maxLength: 64 }), name: Type.String({ minLength: 1, maxLength: 100 }), value: Type.String({ minLength: 1, maxLength: 255 }), sortOrder: Type.Optional(Type.Integer()), color: Type.Optional(Type.Union([Type.String({ maxLength: 32 }), Type.Null()])), icon: Type.Optional(Type.Union([Type.String({ maxLength: 100 }), Type.Null()])), isDefault: Type.Optional(Type.Boolean()), enabled: Type.Optional(Type.Boolean()), remark: Type.Optional(Type.Union([Type.String({ maxLength: 500 }), Type.Null()])) }, { additionalProperties: false });
export const ItemSchema = Type.Object({ id: Type.Integer({ minimum: 1 }), categoryId: Type.Integer({ minimum: 1 }), code: Type.String(), name: Type.String(), value: Type.String(), sortOrder: Type.Integer(), color: Type.Union([Type.String(), Type.Null()]), icon: Type.Union([Type.String(), Type.Null()]), isDefault: Type.Boolean(), enabled: Type.Boolean(), remark: Type.Union([Type.String(), Type.Null()]) });
export const CategorySchema = Type.Object({ id: Type.Integer({ minimum: 1 }), code: Type.String(), description: Type.Union([Type.String(), Type.Null()]), sortOrder: Type.Integer(), enabled: Type.Boolean(), items: Type.Array(ItemSchema) });
export type CodeParams = Static<typeof CodeParamsSchema>; export type IdParams = Static<typeof IdParamsSchema>; export type CategoryBody = Static<typeof CategoryBodySchema>; export type CategoryUpdateBody = Static<typeof CategoryUpdateBodySchema>; export type ItemBody = Static<typeof ItemBodySchema>;
